### ISSUE TITLE
"Link needs app" and "permission denied"

### ISSUE THREAD

**Issue by zacguide** [meriadec/linux-install-instructions#2]
Trying to download Ledger Live. Unsuccessful so contacted Ledger support and reported the first issue below. They recommended this patch. Basically, I have been following their instructions.

First download try, and try after this patch result were same "Link needs to be opened with an app" and the field under is blank. See 1st screenshot.

![screenshot from 2018-12-31 20-02-22](https://user-images.githubusercontent.com/46448609/50774656-94283b80-12c6-11e9-80d8-1e3712d6ef3e.png)

Tried troubleshooting and get the response "access denied." See 2nd screenshot.

![screenshot from 2019-01-05 15-37-44](https://user-images.githubusercontent.com/46448609/50774693-a99d6580-12c6-11e9-8510-b4d0c8e60408.png)

Ledger then recommended starting a ticket here.

Thanks, Zach

**Comment by meriadec** [comment]
1) as described in the [Linux installation instructions](https://support.ledger.com/hc/en-us/articles/360006395553-Download-and-install-Ledger-Live) when you download the binary file, you first have to change it's permissions to executable before launching it

```
chmod +x ledger-live-*.AppImage
```

2. I don't get why you try to execute the udev rules file :thinking: did you ensure that the [automatic install script](https://github.com/meriadec/nanos-linux-install-instructions/blob/master/README.md#2-add-the-udev-rules) didn't work?

**Comment by zacguide** [comment]
I am sorry I am so inexperienced. I tried to execute the udev rules file
because I was instructed to by the Ledger support team based on the results
of the 1st download attempt. He directed me to the udev rules file page on
github. I don't know enough to know this was useless even though it did
seem to me the problem is more simple.

Thanks. I will try the instructions link and see how that goes.

Zach

**Comment by meriadec** [comment]
no problem! don't worry. Given your screenshot you seems to be on Ubuntu and just executing the udev rules install script should be good :)

**Comment by meriadec** [comment]
So to sum up:

1) Download the app from https://www.ledger.com/pages/ledger-live
2) Open a terminal, go to your downloads folder, and set executable permission on the downloaded file:

```
chmod +x ledger-live-*.AppImage
```

3) Setup udev rules by executing this:

```
wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
```

(ensure you copied all the line, there is an horizontal scroll)

4) Launch the app (either from the console: `./ledger-live-*.AppImage` or by double click

**Comment by zacguide** [comment]
Thank you. I very much appreciate your help.

One problem and one question.

First, a very simple question from a total beginner... when I am in terminal, how do I go to the Downloads file?

The problem... I download from the Ledger link, file says it completes. But the file is neither in the downloads file nor in the archive file. Unzipped archive files by default get sent to archive manager. I checked both places and the file isn't in either. I just get the same box every time asking for an app to open the link with no apps shown in the box below to choose from.

**Comment by meriadec** [comment]
ok so first, download by right click and save as, and choose a location that you know.

![test](https://user-images.githubusercontent.com/315259/50843600-43b5ea00-1369-11e9-9550-721c79186b02.png)

then go to your file explorer, navigate to the folder you just chosen, and right-click -> open terminal here.

then you can do the `chmod` thing, then launch the app.

**Comment by zacguide** [comment]
Thank you. I very much appreciate your help.

One problem and one question.

First, a very simple question from a total beginner... when I am in terminal, how do I go to the Downloads file?

The problem... I download from the Ledger link, file says it completes. But the file is neither in the downloads file nor in the archive file. Unzipped archive files by default get sent to archive manager. I checked both places and the file isn't in either. I just get the same box every time asking for an app to open the link with no apps shown in the box below to choose from.

**Comment by zacguide** [comment]
Ok, progress...

I downloaded it into Download folder so now it shows up there. However, when I right click, I don`'t get the "open terminal here" option. That would be great though. Just the options to open or open with application.

**Comment by meriadec** [comment]
ye. you may right click on your file explorer to get "open terminal here"
alternatively, you can also open a terminal then `cd ~/Downloads`

**Comment by zacguide** [comment]
Success!

Thanks for your help. It would be nice if the "open in terminal" option was displayed in the right click drop down menu. I had to access it via terminal. But I don't know how to configure things yet. Anyway, all is working well. Happy new year and thanks for your patience and explicit instructions including 2 ways to complete each step.

**Comment by meriadec** [comment]
Glad you figured out :tada: happy new year too!
